version: "3"

services:

  ceph-demo:
    image: quay.io/ceph/demo:latest-quincy
    environment:
      CEPH_DEMO_UID: "demo"
      CEPH_DEMO_ACCESS_KEY: "demo"
      CEPH_DEMO_SECRET_KEY: "demo"
      CEPH_DEMO_BUCKET: "demo"
      CEPH_PUBLIC_NETWORK: "0.0.0.0/0"
      MON_IP: "127.0.0.1"
      RGW_NAME: "localhost"
    ports:
      - "8080:8080"